import React, { useEffect, useState } from "react";

const PrintNum = ({ number }) => {
  // State to store the array of numbers generated by the `number` function
  const [data, setData] = useState([]);

  // `useEffect` to update the `data` state whenever the `number` function changes
  useEffect(() => {
    console.log("child element called"); // Log to indicate when the child component re-renders
    setData(number()); // Call the `number` function and update the `data` state
  }, [number]); // Dependency array ensures this effect runs only when `number` changes

  return (
    <div>
      {/* Render each number in the `data` array as a list item */}
      {data.map((num, index) => (
        <li key={index}>{num}</li> // Use `index` as the key since the array elements are simple numbers
      ))}
    </div>
  );
};

export default PrintNum;
